type HeadProps = {
  title: string;
};

const Head = ({ title }: HeadProps) => (
  <head>
    <meta charSet="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
    />
    <title>{title}</title>
    <meta name="description" content="Generated by create turbo" />
  </head>
);

export default Head;
